name: C/C++ CI

on:
  push:
    branches: [ "main", "Lab4" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: | 
           cd ./Lab3/ 
           make clean
           make
    - name: Checkout
      run: |
           if ./main | grep -q "55"; then
           echo "yes"
           fi

    

